sudo: required
dist: xenial
addons:
  chrome: stable
  firefox: latest
language: node_js
services:
- xvfb
cache:
  yarn: true
node_js:
- '8'
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: HS+XKf6cgtVAh3DuLk63Ivau7NXk5E+GB67GU4nYtW7k3Q/jjcbfyprDmX8erD5nAeR/egFLrzUGQVqipWNFIU5MZi8naghuXY/adEKvPTJ/gwNXkZRS0QZzq5Jv0o7j+mfeHRdu78VcwUFzTjr2WBUq6QX1ra+sBo5kmRhoYv2F7jMn+24CEvhK0Vx7n5iYnNGLcP3nKkwRpRNbWxHGK4r0HAGfS3JrgrZGHClIlvzNRomTQy3RObppiqlQjJsebCobtgBOvB33KrpsnG0wCeyrkkAH+/u6IuXSSLibGqprd7todDZTrGRKWg2faicTZ9zZ+DTpSX/1xBWotIgmusIsV8jINQtnHoRp0BXHvcx5wkmFCo73T/squleQhss6wQkeJnOZkQEd0P6CpTQGvrJZjSUxv1pboyEeWgjB86b6jnNefys4GadZE7mbE6cYaKzXGEJMFclH4OBw4uF/VadC75ZEpoIK8YOk8ccSp+bvb3KzrYequrS+b7XidwEPrI4HLC4MESqEfHTKIKZro+Db2xgkxS0ZJl1KF7e8UMW3Zkh5a9AZ8sOrYUmJGVm3LjDeKCa4fe/C/vEEyxVksSZa/Wc440agp4caevbg9ksQ6PfkV6TGLyphhVAYEdT3i7ZiwdwRrU2RTuT35M/3Y6dOJVZGoIW7/LhCD6TRrDw=
